### ISSUE TITLE
Mensagem errada na tooltip de IOF

### ISSUE THREAD

**Issue by kauehadzic** [TrindadeTecnologia/painel-corretor-management#12]
Erro ao ver o alt do valor com iof. 

![image](https://user-images.githubusercontent.com/30120657/37175359-10170dbc-22f8-11e8-825a-bdaf977f79d6.png)

**Comment by oliveiracdz** [comment]
This issue was moved to TrindadeTecnologia/painel-vue#9

**Comment by oliveiracdz** [comment]
This issue was moved to TrindadeTecnologia/painel-vue#21
