### ISSUE TITLE
Adicionar "fechar" as modals

### ISSUE THREAD

**Issue by kauehadzic** [TrindadeTecnologia/painel-corretor-management#13]
Colocar o "x" nas modals.
Exemplo: Seleção de planos, assinatura.

**Comment by oliveiracdz** [comment]
Seguindo a especificação do Material, seria um botão "voltar" ou "cancelar":
https://material.io/guidelines/components/dialogs.html#dialogs-full-screen-dialogs

**Comment by oliveiracdz** [comment]
This issue was moved to TrindadeTecnologia/painel-vue#22
