### ISSUE TITLE
Mesclagem de passos Vídeo. 

### ISSUE THREAD

**Issue by kauehadzic** [TrindadeTecnologia/painel-corretor-management#4]
- Conceituação.
- Storyboard.
- Busca por Template.
- Ajustes.
- Inicio customização.
- Criação de vetores específicos.
- Andamento das funcionalidades.
- Ajuste de tempo.
- Ajuste de Efeitos.
- Finalização animação.

**Comment by oliveiracdz** [comment]
This issue was moved to TrindadeTecnologia/painel-vue#13
