### ISSUE TITLE
Revisão nos conteúdos de transição

### ISSUE THREAD

**Issue by kauehadzic** [TrindadeTecnologia/painel-corretor-management#8]
*Boa Pratica: Ser claro nos conteúdos, informando que a transição vai ser obrigatória. 

- [ ] Criação e Revisão conteúdo modal e primeiro a-mail.
- [ ] Criação e Revisão conteúdo e-mail Lembrete 1

**Comment by oliveiracdz** [comment]
This issue was moved to TrindadeTecnologia/painel-vue#17
